[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
upload_port = /dev/cu.usbserial-0001
upload_speed = 115200
monitor_speed = 921600
build_flags = -O3 -ffp-contract=off -Wall -Wextra
build_unflags = -Os
