[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 20000000L
board_build.flash_mode = dio
board_build.partitions = partitions.csv
upload_port = /dev/cu.usbserial-0001
upload_speed = 460800
monitor_speed = 460800
build_flags = -O3 -ffp-contract=off -Wall -Wextra
build_unflags = -Os
board_build.arduino.custom_bootloader = /Users/luongnguyenthanhhung/Documents/AI4IoT/Tieu_luan_mon_hoc/firmware/esp32_baselines/bootloader_20m.bin
